use std::fs;
use std::path::{Path, PathBuf};

use tauri::{AppHandle, State};

use crate::core::jsonl::create_jsonl_with_schema;
use crate::core::types::Config;
use crate::core::watcher::start_watcher;
use crate::state::AppState;

/// Create the workspace directory structure and starter files.
/// Reusable by both init_workspace and onboarding.
pub fn create_workspace_structure(root: &Path, active_tools: &[String]) -> Result<Config, String> {
    // Create all directories
    let dirs = [
        "01-context",
        "02-daily",
        "02-daily/sessions",
        "03-intelligence",
        "04-projects",
        "05-resources",
        "06-skills",
        "07-tasks",
        "08-rules",
        "09-scratch",
        ".cache",
    ];

    for dir in &dirs {
        fs::create_dir_all(root.join(dir))
            .map_err(|e| format!("Failed to create {}: {}", dir, e))?;
    }

    // Create _config.yaml
    let config = Config {
        root_dir: root.to_string_lossy().to_string(),
        default_token_budget: 4000,
        decay_threshold: 0.1,
        scratch_ttl_days: 7,
        active_tools: if active_tools.is_empty() {
            vec!["claude".to_string()]
        } else {
            active_tools.to_vec()
        },
    };
    let config_yaml = serde_yaml::to_string(&config)
        .map_err(|e| format!("Failed to serialize config: {}", e))?;
    fs::write(root.join("_config.yaml"), config_yaml)
        .map_err(|e| format!("Failed to write _config.yaml: {}", e))?;

    // Create initial claude.md
    let initial_router = r#"# AI Context OS — Router

Este archivo se genera automáticamente. No editar manualmente.

> Sistema inicializado. Añade memorias para ver el índice aquí.

# RULES

_No hay reglas definidas. Añade archivos en 08-rules/_

# Reglas de Lectura y Escritura de Memorias

## Lectura
1. Lee SOLO los archivos que necesites para la tarea actual
2. Empieza siempre por el nivel L1 (resumen)
3. Carga L2 (completo) SOLO si L1 no tiene suficiente detalle
4. NUNCA cargues más de 5 archivos L2 en una sola consulta
5. Prioriza: rules > context > skills > projects > resources

## Escritura
- Usa frontmatter YAML estándar (id, type, l0, importance, tags, related)
- Separa contenido con <!-- L1 --> y <!-- L2 -->
- Incrementa version: y actualiza modified: al editar

# Índice de Memorias Disponibles

_No hay memorias aún. Crea tu primera memoria desde la app._
"#;
    fs::write(root.join("claude.md"), initial_router)
        .map_err(|e| format!("Failed to write claude.md: {}", e))?;

    // Create JSONL files with schema lines
    create_jsonl_with_schema(
        &root.join("02-daily/daily-log.jsonl"),
        "timestamp,type,summary,tags,source",
    )?;
    create_jsonl_with_schema(
        &root.join("07-tasks/backlog.jsonl"),
        "timestamp,id,title,status,priority,tags",
    )?;

    // Create _index.yaml
    let index = "# AI Context OS — Index L0 (autogenerated)\n# Do not edit manually\n\nmemories: []\n";
    fs::write(root.join("_index.yaml"), index)
        .map_err(|e| format!("Failed to write _index.yaml: {}", e))?;

    // Create skill instructions file
    let skill_instructions = r#"---
id: _skill-instructions
type: skill
l0: "Instrucciones para crear y usar skills"
importance: 0.7
tags: [meta, skills, instrucciones]
---

<!-- L1 -->
Los skills son instrucciones reutilizables que la IA ejecuta bajo demanda.
Cada skill sabe qué memorias necesita (campo requires/optional).

<!-- L2 -->
## Cómo crear un skill

1. Crea un archivo .md en 06-skills/
2. Añade frontmatter con: id, type: skill, triggers, requires, optional
3. Escribe las instrucciones detalladas en la sección L2
4. El sistema cargará automáticamente las memorias requeridas
"#;
    fs::write(root.join("06-skills/_skill-instructions.md"), skill_instructions)
        .map_err(|e| format!("Failed to write skill instructions: {}", e))?;

    Ok(config)
}

pub fn read_config_from_root(root: &Path) -> Result<Option<Config>, String> {
    let config_path = root.join("_config.yaml");
    if !config_path.exists() {
        return Ok(None);
    }
    let content = fs::read_to_string(&config_path)
        .map_err(|e| format!("Failed to read config {}: {}", config_path.display(), e))?;
    let config: Config = serde_yaml::from_str(&content)
        .map_err(|e| format!("Failed to parse config {}: {}", config_path.display(), e))?;
    Ok(Some(config))
}

fn expand_home(path: &str) -> PathBuf {
    if path == "~" {
        return dirs::home_dir().unwrap_or_else(|| PathBuf::from("."));
    }
    if let Some(rest) = path.strip_prefix("~/") {
        if let Some(home) = dirs::home_dir() {
            return home.join(rest);
        }
    }
    PathBuf::from(path)
}

pub fn sync_workspace_runtime(state: &crate::state::AppState, app: Option<&AppHandle>) -> Result<(), String> {
    state.refresh_memory_index();

    if let Err(e) = state.rebind_observability() {
        state.clear_observability();
        log::warn!("Failed to initialize observability DB for {}: {}", state.get_root().display(), e);
    }

    if let Some(app) = app {
        let root = state.get_root();
        if root.exists() {
            match start_watcher(root.clone(), app.clone(), Some(state.memory_index.clone())) {
                Ok(handle) => state.replace_watcher(Some(handle)),
                Err(e) => {
                    state.replace_watcher(None);
                    log::warn!("Failed to start watcher on {}: {}", root.display(), e);
                }
            }
        } else {
            state.replace_watcher(None);
        }
    }

    Ok(())
}

/// Initialize the workspace directory structure.
#[tauri::command]
pub fn init_workspace(app: AppHandle, state: State<AppState>) -> Result<bool, String> {
    let root = state.get_root();

    if root.join("claude.md").exists() {
        return Ok(false);
    }

    let config = create_workspace_structure(&root, &[])?;
    state.set_root(root.clone())?;
    *state.config.write().unwrap() = config;
    sync_workspace_runtime(state.inner(), Some(&app))?;

    Ok(true)
}

/// Get the current configuration.
#[tauri::command]
pub fn get_config(state: State<AppState>) -> Result<Config, String> {
    let root = state.get_root();
    if let Some(config) = read_config_from_root(&root)? {
        *state.config.write().unwrap() = config.clone();
        Ok(config)
    } else {
        Ok(state.config.read().unwrap().clone())
    }
}

/// Save configuration.
#[tauri::command]
pub fn save_config(config: Config, app: AppHandle, state: State<AppState>) -> Result<(), String> {
    let root = if config.root_dir.trim().is_empty() {
        state.get_root()
    } else {
        expand_home(&config.root_dir)
    };
    fs::create_dir_all(&root)
        .map_err(|e| format!("Failed to create workspace root {}: {}", root.display(), e))?;

    let config_yaml = serde_yaml::to_string(&config)
        .map_err(|e| format!("Failed to serialize config: {}", e))?;
    fs::write(root.join("_config.yaml"), config_yaml)
        .map_err(|e| format!("Failed to write config: {}", e))?;
    state.set_root(root)?;
    *state.config.write().unwrap() = config;
    sync_workspace_runtime(state.inner(), Some(&app))?;
    Ok(())
}
