/// Render adapter output for Claude Desktop / Claude Code / Co-Work (writes to claude.md).
pub fn render_claude_adapter(data: &str) -> String {
    let mut out = String::from("# AI Context OS — Claude Adapter Router\n");
    out.push_str(
        "# Auto-generated. Do not edit — this is a derived router artifact, not a canonical memory file.\n",
    );
    out.push_str(
        "# Do not store notes, scratch content, or permanent instructions here; edit canonical memories instead.\n\n",
    );
    out.push_str(data);
    out
}

/// Render adapter output for Cursor IDE (writes to .cursorrules).
pub fn render_cursor_adapter(data: &str) -> String {
    let mut out = String::from("# AI Context OS — Cursor Adapter\n");
    out.push_str("# Auto-generated by AI Context OS. Do not edit manually.\n\n");
    out.push_str(data);
    out
}

/// Render adapter output for Windsurf IDE (writes to .windsurfrules).
pub fn render_windsurf_adapter(data: &str) -> String {
    let mut out = String::from("# AI Context OS — Windsurf Adapter\n");
    out.push_str("# Auto-generated by AI Context OS. Do not edit manually.\n\n");
    out.push_str(data);
    out
}

/// Render adapter output for tools following the AGENTS.md convention
/// (Codex, Aider, Jules, Continue, Cline and others). Writes to AGENTS.md.
pub fn render_agents_adapter(data: &str) -> String {
    let mut out = String::from("# AGENTS.md\n");
    out.push_str(
        "# Auto-generated by AI Context OS. Do not edit manually — this is a derived router artifact.\n",
    );
    out.push_str(
        "# Universal operating manual for agents in this workspace, not a place to store notes or repo-specific instructions.\n\n",
    );
    out.push_str(data);
    out
}
