/// Render adapter output for Claude Desktop / Claude Code / Co-Work (writes to claude.md).
pub fn render_claude_adapter(data: &str) -> String {
    let mut out = String::from("# AI Context OS — Master Router\n");
    out.push_str(
        "# Auto-generated. Do not edit — changes are overwritten on every memory operation.\n",
    );
    out.push_str("# This file is your operating manual for this workspace.\n\n");
    out.push_str(data);
    out
}

/// Render adapter output for Cursor IDE (writes to .cursorrules).
pub fn render_cursor_adapter(data: &str) -> String {
    let mut out = String::from("# AI Context OS — Cursor Adapter\n");
    out.push_str("# Auto-generated by AI Context OS. Do not edit manually.\n\n");
    out.push_str(data);
    out
}

/// Render adapter output for Windsurf IDE (writes to .windsurfrules).
pub fn render_windsurf_adapter(data: &str) -> String {
    let mut out = String::from("# AI Context OS — Windsurf Adapter\n");
    out.push_str("# Auto-generated by AI Context OS. Do not edit manually.\n\n");
    out.push_str(data);
    out
}
