/// Render adapter output for Claude Desktop / Claude Code (writes to claude.md).
pub fn render_claude_adapter(data: &str) -> String {
    let mut out = String::from("# AI Context OS — Claude Adapter\n");
    out.push_str("# Auto-generated by AI Context OS. Do not edit manually.\n\n");
    out.push_str(data);
    out
}

/// Render adapter output for Cursor IDE (writes to .cursorrules).
pub fn render_cursor_adapter(data: &str) -> String {
    let mut out = String::from("# AI Context OS — Cursor Adapter\n");
    out.push_str("# Auto-generated by AI Context OS. Do not edit manually.\n\n");
    out.push_str(data);
    out
}

/// Render adapter output for Windsurf IDE (writes to .windsurfrules).
pub fn render_windsurf_adapter(data: &str) -> String {
    let mut out = String::from("# AI Context OS — Windsurf Adapter\n");
    out.push_str("# Auto-generated by AI Context OS. Do not edit manually.\n\n");
    out.push_str(data);
    out
}
